컴파일 에러
throws IOException을 선언해야 에러가 안뜸


 import java.io.*;

public class Test {

  public static void main(String[] args) {
    int n=10;
    int[] v = new int[n];

    try{
    FileReader f = new FileReader("dati.txt");
    BufferedReader in = new BufferedReader(f);
    int i=0;
    String linea = in.readLine();
    while (linea!=null) {
      v[i] = Integer.parseInt(linea);
      linea = in.readLine();
      i++;
    }
    f.close();
  }catch(FileNotFoundException e){
    System.out.println(e.getMessage());
  }catch (IOException e){
    System.out.println(e.getMessage());
  }
}
}
//catch문 순서를 바꾸면 Unreachable catch block for FileNotFoundException. It is already handled by the catch block for IOException가 뜸